version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/docker/rl-agent/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/docker/px4-bridge/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/docker/px4-simulator/"
    schedule:
      interval: "weekly" 