services:
  drone_msgs:
    build:
      context: .
      dockerfile: docker/Dockerfile.msgs
      args:
        BUILDKIT_INLINE_CACHE: 1
    platform: linux/arm64
    volumes:
      - ./src/drone_msgs:/workspace/src/drone_msgs:ro
      - ./src/px4_msgs:/workspace/src/px4_msgs:ro
      - ./install:/workspace/install
    environment:
      - COLCON_OPTIONS=--packages-select drone_msgs px4_msgs --parallel-workers 1

  bridge:
    build:
      context: .
      dockerfile: docker/Dockerfile.bridge
      args:
        BUILDKIT_INLINE_CACHE: 1
    platform: linux/arm64
    volumes:
      - ./src:/workspace/src:ro
      - ./install:/workspace/install
      - ./config:/workspace/config:ro
    environment:
      - COLCON_OPTIONS=--packages-select common command_bridge state_bridge --parallel-workers 1
    depends_on:
      - drone_msgs

  manual_control:
    build:
      context: .
      dockerfile: docker/Dockerfile.manual_control
      args:
        BUILDKIT_INLINE_CACHE: 1
    platform: linux/arm64
    volumes:
      - ./src/manual_control:/workspace/src/manual_control:ro
      - ./config:/workspace/config:ro
      - ./logs/manual_control:/manual_ws/log
    depends_on:
      - bridge
    healthcheck:
      test: ["CMD-SHELL", "ps -e | grep simple_simulator || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  web_viz:
    build:
      context: .
      dockerfile: docker/Dockerfile.web_viz
      args:
        BUILDKIT_INLINE_CACHE: 1
    platform: linux/arm64
    ports:
      - "8080:8080"
    volumes:
      - ./web_viz:/workspace/web_viz:ro
      - ./logs/web_viz:/var/log/web_viz
    depends_on:
      - bridge
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/", "||", "exit", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

networks:
  default:
    name: manual_control_network 