# Simulation parameters
simulation:
  headless: true
  gazebo_verbose: false
  px4_sitl_args: ""

# ROS parameters
ros:
  domain_id: 0
  topic_prefix: "/drone0"

# Bridge parameters
bridge:
  state_publish_rate: 10.0  # Hz
  control_timeout: 1.0      # seconds 