# 共通環境変数
x-common-env: &common-env
  ROS_DOMAIN_ID: 0
  PYTHONPATH: /workspace/src
  DISPLAY: ${DISPLAY:-:0}

# 共通ボリューム
x-common-volumes: &common-volumes
  - ./drone-sim-core/src:/workspace/src:ro
  - ./drone-sim-core/config:/workspace/config:ro

services:
  # メッセージビルドサービス
  msgs:
    build:
      context: ..
      dockerfile: drone-sim-core/docker/Dockerfile.msgs
      target: runtime
    image: drone-avoidance:msgs
    profiles: ["default", "test"]
    volumes: *common-volumes
    environment: *common-env
    command: ["tail", "-f", "/dev/null"]
    healthcheck:
      test: ["CMD", "ls", "/msgs_ws/install/lib/python3.10/site-packages/drone_msgs/msg/_drone_control_command.py"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Bridge サービス
  bridge:
    build:
      context: ..
      dockerfile: drone-sim-core/docker/Dockerfile.bridge
      target: runtime
    image: drone-avoidance:bridge
    profiles: ["default", "test"]
    depends_on:
      msgs:
        condition: service_healthy
    volumes: *common-volumes
    environment: *common-env
    command: ["ros2", "run", "state_bridge", "state_bridge_node"]
    healthcheck:
      test: ["CMD", "ros2", "node", "list"]
      interval: 10s
      timeout: 5s
      retries: 5

# --- Swarm/Multi-agent profile example ---
# 複数ドローンを起動する場合のテンプレート例
# docker-compose --profile swarm up で有効化
#
# services:
#   drone1:
#     <<: *common-env
#     image: drone-avoidance:drone
#     environment:
#       DRONE_NAMESPACE: /drone_1
#     profiles: ["swarm"]
#     command: ["ros2", "run", "state_bridge", "state_bridge_node", "--ros-args", "-r", "__ns:=/drone_1"]
#   drone2:
#     <<: *common-env
#     image: drone-avoidance:drone
#     environment:
#       DRONE_NAMESPACE: /drone_2
#     profiles: ["swarm"]
#     command: ["ros2", "run", "state_bridge", "state_bridge_node", "--ros-args", "-r", "__ns:=/drone_2"]
#   ...
#
# docker-compose --profile swarm up で複数インスタンスを起動可能
# ネットワーク設定
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 