name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-cpu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -c "from gym_env import register_drone_env; register_drone_env()"
        python -c "import gymnasium as gym; env=gym.make('DroneSimEnv-v0'); print('Environment test OK')"

  build-docker:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build CPU image
      run: |
        docker build -f docker/rl-agent-cpu/Dockerfile -t drone-rl:cpu .

    - name: Test CPU image
      run: |
        docker run --rm drone-rl:cpu

  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install linting tools
      run: |
        pip install ruff mypy

    - name: Run linting
      run: |
        ruff check . --output-format=json || true

    - name: Run type checking
      run: |
        mypy . --ignore-missing-imports || true 