# .drone.github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build & run stack (headless)
        run: |
          docker compose --profile cpu up -d --build px4-simulator px4-bridge rl-agent
          until docker compose ps | grep px4-bridge | grep '(healthy)'; do sleep 5; done

      - name: Run pytest inside rl-agent
        run: docker compose exec rl-agent pytest -q /work/tests
