# 分散強化学習設定
rl:
  # 基本設定
  algorithm: "PPO"  # PPO, SAC, TD3, DQN
  framework: "torch"  # torch, tf
  
  # 環境設定
  env:
    num_envs: 8  # 並列環境数
    vector_env: true
    max_episode_steps: 1000
    
  # 学習設定
  training:
    total_timesteps: 10000000
    batch_size: 256
    learning_rate: 3e-4
    gamma: 0.99
    gae_lambda: 0.95
    
  # 分散学習設定
  distributed:
    num_workers: 4
    num_gpus: 1
    backend: "nccl"  # nccl, gloo
    
  # チェックポイント設定
  checkpoint:
    frequency: 10000
    keep_last_n: 5
    
  # 監視設定
  monitoring:
    tensorboard: true
    wandb: true
    log_interval: 100
    
  # 混合精度学習設定
  mixed_precision:
    enabled: true
    fp16: true
    bf16: false
    gradient_scaling: true
    
  # ハイパーパラメータ
  hyperparameters:
    # PPO
    ppo:
      n_steps: 2048
      n_epochs: 10
      batch_size: 128  # 混合精度で2倍化
      clip_range: 0.2
      vf_coef: 0.5
      ent_coef: 0.01
      
    # SAC
    sac:
      batch_size: 512  # 混合精度で2倍化
      learning_rate: 3e-4
      buffer_size: 1000000
      tau: 0.005
      gamma: 0.99
      train_freq: 1
      gradient_steps: 1
      
    # TD3
    td3:
      batch_size: 512  # 混合精度で2倍化
      learning_rate: 3e-4
      buffer_size: 1000000
      tau: 0.005
      gamma: 0.99
      train_freq: 1
      gradient_steps: 1
      policy_delay: 2 