# 最適化されたシミュレーションパラメータ
gazebo:
  # パフォーマンス最適化
  performance:
    lockstep: true                    # ロックステップモード
    physics_rate: 1000               # 物理演算周波数
    max_step_size: 0.001            # 最大ステップサイズ
    real_time_factor: 1.0           # リアルタイム係数
    
  # センサー最適化
  sensors:
    lidar:
      update_rate: 10               # LiDAR更新周波数（デフォルト: 30Hz）
      range: 50.0                   # 検出範囲
      resolution: 0.1               # 解像度
      
    camera:
      update_rate: 15               # カメラ更新周波数（デフォルト: 30Hz）
      resolution: [640, 480]        # 解像度
      
    imu:
      update_rate: 100              # IMU更新周波数
      
  # 物理エンジン最適化
  physics:
    engine: "ode"                   # 物理エンジン
    max_contacts: 20                # 最大接触数
    contact_surface_layer: 0.001    # 接触面レイヤー
    gravity: [0, 0, -9.81]         # 重力
    
  # レンダリング最適化
  rendering:
    engine: "ogre2"                 # レンダリングエンジン
    anti_aliasing: false            # アンチエイリアス無効
    shadows: false                  # シャドウ無効
    ambient_light: [0.4, 0.4, 0.4] # 環境光
    
  # ネットワーク最適化
  network:
    ros_domain_id: 0               # ROS 2ドメインID
    dds_qos_profile: "fast"        # DDS QoSプロファイル
    
  # メモリ最適化
  memory:
    max_memory: 4096               # 最大メモリ使用量（MB）
    gc_frequency: 1000             # ガベージコレクション頻度
    
  # デバッグ設定
  debug:
    verbose: false                  # 詳細ログ無効
    profile: false                  # プロファイリング無効 