name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup ROS 2 Humble
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:ros/ppa
        sudo apt update
        sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions

    - name: Source ROS 2
      run: |
        echo "source /opt/ros/humble/setup.bash" >> $GITHUB_ENV

    - name: Build
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Test
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --packages-select drone_msgs px4_msgs
        colcon test-result --verbose

    - name: Lint
      run: |
        # Check for common issues
        find . -name "*.msg" -exec echo "Checking {}" \; -exec head -5 {} \;
        echo "Message files checked successfully" 