name: Integration CI

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * 1"  # 毎週月曜 03:00 UTC

jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & Run Integration Tests
      run: |
        docker compose -f docker-compose.yml build
        docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from rl-agent

    - name: Cleanup
      if: always()
      run: |
        docker compose -f docker-compose.yml down -v 