version: '3.8'

services:
  msgs:
    build:
      context: ./external/drone-msgs
      dockerfile: Dockerfile.msgs
    image: drone-msgs:ci
    healthcheck:
      test: ["CMD", "bash", "-c", "ls /msgs_ws/install/lib/python*/site-packages/drone_msgs"]
      interval: 10s
      timeout: 5s
      retries: 5

  sim:
    build:
      context: ./external/drone-sim-core
      dockerfile: docker/Dockerfile.base
    image: drone-sim-core:ci
    depends_on:
      msgs:
        condition: service_healthy
    environment:
      ROS_DOMAIN_ID: 0
    command: >
      bash -c "source /opt/ros/humble/setup.sh && ros2 launch sim_launch sim_all.launch.py headless:=true"

  bridge:
    build:
      context: ./external/drone-sim-core
      dockerfile: docker/Dockerfile.bridge
    image: drone-bridge:ci
    depends_on:
      sim:
        condition: service_healthy
    environment:
      ROS_DOMAIN_ID: 0
    command: >
      bash -c "source /opt/ros/humble/setup.sh && ros2 run state_bridge state_bridge_node"

  rl-agent:
    build:
      context: ./external/drone-rl
      dockerfile: docker/rl-agent-cpu/Dockerfile
    image: drone-rl:ci
    depends_on:
      bridge:
        condition: service_healthy
    environment:
      PYTHONPATH: /workspace
    command: ["python", "-m", "pytest", "tests/test_gym_api.py", "-q"] 