name: Orchestrated CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_integration:
        description: 'Run integration tests'
        required: false
        default: false
        type: boolean

jobs:
  # 各リポジトリの独立テスト
  test-drone-msgs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        path: drone-msgs
    - name: Setup ROS 2
      run: |
        cd drone-msgs
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:ros/ppa
        sudo apt update
        sudo apt install -y ros-humble-ros-base python3-colcon-common-extensions
    - name: Test drone-msgs
      run: |
        cd drone-msgs
        source /opt/ros/humble/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release
        echo "drone-msgs build successful"

  test-drone-sim-core:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        path: drone-sim-core
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Test drone-sim-core
      run: |
        cd drone-sim-core
        docker compose config
        echo "drone-sim-core configuration valid"

  test-drone-rl:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        path: drone-rl
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd drone-rl
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test drone-rl
      run: |
        cd drone-rl
        # Register environment and run tests
        python -c "from gym_env import register_drone_env; register_drone_env()"
        python -c "import gymnasium as gym; env=gym.make('DroneSimEnv-v0'); print('Environment test OK')"
        python -m pytest tests/test_gym_api.py -v
    - name: Build Docker image
      run: |
        cd drone-rl
        docker build -f docker/rl-agent-cpu/Dockerfile -t drone-rl:cpu .
        docker run --rm drone-rl:cpu

  # 統合テスト（条件付き実行）
  integration-test:
    runs-on: ubuntu-22.04
    needs: [test-drone-msgs, test-drone-sim-core, test-drone-rl]
    if: |
      github.event_name == 'workflow_dispatch' && 
      github.event.inputs.run_integration == 'true'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Run Integration Tests
      run: |
        cd integration-tests
        docker compose build
        docker compose up --abort-on-container-exit 