name: CI

on:
  push:
    branches:
      - main
      - fix/**         # ← ★ ここを追加して、fix 系ブランチの push もトリガーに
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build (no cache)
        run: docker compose build --no-cache

      - name: Up
        run: docker compose --profile cpu up -d

      - name: pytest
        run: docker compose exec -T rl-agent pytest -q /work/tests

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: logs
