name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-msgs:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-msgs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-msgs-

      - name: Build msgs_ws stage
        run: |
          docker build \
            --target msgs_ws \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache-new \
            -f docker/Dockerfile.msgs .

      - name: Move updated cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  
  e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Launch simulation and test
        run: docker compose -f tests/ci-compose.yml up --abort-on-container-exit

