name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  rosdep-consistency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install pyyaml
        run: pip install pyyaml types-PyYAML
      - name: Check rosdep YAML consistency
        run: python3 tools/check_rosdep_consistency.py 