name: Manual Control CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'drone_manual_control/**'
      - 'models/**'
      - 'docker/**'
      - 'config/**'
      - '.github/workflows/manual-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'drone_manual_control/**'
      - 'models/**'
      - 'docker/**'
      - 'config/**'
      - '.github/workflows/manual-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          python3-pip \
          python3-dev \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
          
    - name: Install Docker
      run: |
        # Docker公式のインストールスクリプトを使用
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        # Docker Composeをインストール
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Install ROS 2 Humble
      run: |
        sudo apt update && sudo apt install software-properties-common
        sudo add-apt-repository universe
        sudo apt update && sudo apt install curl
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install ros-humble-desktop python3-colcon-common-extensions
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r drone_manual_control/requirements.txt
        
    - name: Build ROS 2 packages
      run: |
        # Clean previous build artifacts
        rm -rf build/ install/ log/
        
        # Check available packages
        echo "Available packages in src/:"
        ls -la src/
        
        # Source ROS 2 environment
        source /opt/ros/humble/setup.bash
        
        # Build packages with explicit workspace
        colcon build --packages-select drone_msgs px4_msgs common manual_control --build-base build --install-base install
        
    - name: Run linting for manual control
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        flake8 drone_manual_control/src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        mypy drone_manual_control/src/ --config-file=mypy.ini
        
    - name: Run unit tests for manual control
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        python -m pytest drone_manual_control/tests/ -v
        
    - name: Build Docker images for manual control
      run: |
        cd drone_manual_control
        docker build -f docker/Dockerfile.manual_control -t drone-manual-control .
        docker build -f docker/Dockerfile.msgs -t drone-manual-msgs .
        docker build -f docker/Dockerfile.bridge -t drone-manual-bridge .
        
    - name: Run integration tests for manual control
      run: |
        cd drone_manual_control
        docker-compose -f tests/ci-compose.yml up -d
        sleep 30
        docker-compose -f tests/ci-compose.yml logs
        docker-compose -f tests/ci-compose.yml down
        
    - name: Test action sequences
      run: |
        cd drone_manual_control
        python -c "
        import yaml
        with open('config/action_sequences.yaml', 'r') as f:
            data = yaml.safe_load(f)
        assert 'action_sequences' in data, 'action_sequences not found'
        assert len(data['action_sequences']) > 0, 'No action sequences defined'
        print(f'Found {len(data[\"action_sequences\"])} action sequences')
        "
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: manual-test-results
        path: |
          drone_manual_control/test-results/
          drone_manual_control/coverage.xml
          
  deployment-test:
    runs-on: ubuntu-22.04
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test deployment
      run: |
        cd drone_manual_control
        # デプロイメントテスト（実際の環境に応じて調整）
        echo "Testing deployment configuration..."
        docker-compose config
        
    - name: Validate configuration files
      run: |
        cd drone_manual_control
        # YAML設定ファイルの検証
        python -c "
        import yaml
        import sys
        
        config_files = [
            'config/action_sequences.yaml',
            'config/sim_params.yaml'
        ]
        
        for config_file in config_files:
            try:
                with open(config_file, 'r') as f:
                    yaml.safe_load(f)
                print(f'✅ {config_file} is valid')
            except Exception as e:
                print(f'❌ {config_file} is invalid: {e}')
                sys.exit(1)
        " 