name: Release

on:
  push:
    branches:
      - main

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test basic file structure
        run: |
          echo "Testing basic file structure..."
          ls -la
          ls -la drone-sim-core/
          ls -la interfaces/
          ls -la drone-rl/
          echo "✅ Basic file structure test passed"

      - name: Test configuration files
        run: |
          echo "Testing configuration files..."
          test -f drone-sim-core/docker-compose.yml && echo "✅ docker-compose.yml exists"
          test -f interfaces/drone_msgs/package.xml && echo "✅ package.xml exists"
          test -f drone-rl/requirements.txt && echo "✅ requirements.txt exists"
          echo "✅ Configuration files test passed"

  release:
    runs-on: ubuntu-latest
    needs: test-basic
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release and plugins (no npm)
        run: |
          npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Run semantic-release (inline config)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ github.workspace }}
          npx semantic-release --branches main --plugins @semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/changelog,@semantic-release/github,@semantic-release/git 