name: Reinforcement Learning CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'models/**'
      - 'docker/**'
      - 'config/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/rl-ci.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'models/**'
      - 'docker/**'
      - 'config/**'
      - 'requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/rl-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          git \
          python3-pip \
          python3-dev \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
          
    - name: Install Docker
      run: |
        # Docker公式のインストールスクリプトを使用
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker $USER
        # Docker Composeをインストール
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        
    - name: Install ROS 2 Humble
      run: |
        sudo apt update && sudo apt install software-properties-common
        sudo add-apt-repository universe
        sudo apt update && sudo apt install curl
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install ros-humble-desktop python3-colcon-common-extensions
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build ROS 2 packages
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --packages-select drone_msgs px4_msgs common
        
    - name: Run linting
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics
        mypy src/ --config-file=mypy.ini
        
    - name: Run unit tests
      run: |
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        python -m pytest tests/ -v
        
    - name: Build Docker images
      run: |
        docker build -f docker/Dockerfile.base -t drone-rl-base .
        docker build -f docker/Dockerfile.msgs -t drone-rl-msgs .
        docker build -f docker/Dockerfile.bridge -t drone-rl-bridge .
        
    - name: Run integration tests
      run: |
        docker-compose -f tests/ci-compose.yml up -d
        sleep 30
        docker-compose -f tests/ci-compose.yml logs
        docker-compose -f tests/ci-compose.yml down
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: rl-test-results
        path: |
          test-results/
          coverage.xml
          
  security-scan:
    runs-on: ubuntu-22.04
    needs: build-and-test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run security scan
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: drone-rl-base
        args: --severity-threshold=high 